services:
  institucional:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./src/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - wisewolf
    labels:
      - traefik.enable=true
      - traefik.docker.network=wisewolf
      - traefik.http.routers.wisewolf-institucional.rule=Host(`wisewolflanguage.com.br`) || Host(`www.wisewolflanguage.com.br`)
      - traefik.http.routers.wisewolf-institucional.entrypoints=websecure
      - traefik.http.routers.wisewolf-institucional.tls.certresolver=le
      - traefik.http.services.wisewolf-institucional.loadbalancer.server.port=80
      - traefik.http.routers.wisewolf-blog-redirect.rule=Host(`blog.wisewolflanguage.com.br`)
      - traefik.http.routers.wisewolf-blog-redirect.entrypoints=websecure
      - traefik.http.routers.wisewolf-blog-redirect.tls.certresolver=le
      - traefik.http.routers.wisewolf-blog-redirect.service=wisewolf-institucional

networks:
  wisewolf:
    external: true
