import React, { useCallback, useEffect, useState } from 'react';
import { ExternalLink, Loader2, RefreshCw, Sparkles } from 'lucide-react';
import { googleMeetAction } from '../lib/googleMeet';
import { describeArtifactImport, googleMeetIssueText, type MeetArtifactImport } from '../lib/googleMeetImports';

export default function LessonPedagogicalSummary({sessionId,tenantId}:{sessionId:string;tenantId?:string}) {
  const [data,setData]=useState<any>(null),[draft,setDraft]=useState<any>(null),[selectedId,setSelectedId]=useState('');
  const [busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[acceptApi,setAcceptApi]=useState(false),[reason,setReason]=useState('');
  const load=useCallback(async()=>{setBusy('load');setError('');try{
    const result:any=await googleMeetAction('session_detail',{sessionId,tenantId});setData(result);
    const latest=result.summaries?.[0];setDraft(latest?.content||null);setSelectedId(latest?.id||'');
  }catch(err){setError((err as Error).message);}finally{setBusy('');}},[sessionId,tenantId]);
  useEffect(()=>{setData(null);setDraft(null);setMessage('');setReason('');setAcceptApi(false);void load();},[load]);
  const run=async(action:string,extra:Record<string,unknown>={})=>{setBusy(action);setError('');setMessage('');try{
    const result:any=await googleMeetAction(action,{sessionId,tenantId,...extra});
    setMessage(action==='review_summary'?(extra.status==='VERIFIED'?'Resumo aprovado e memória do aluno atualizada.':'Revisão registrada.'):action==='sync_artifacts'?`${result.imported?`${result.imported} documento(s) importado(s).`:'Nenhum documento novo disponível. O Google pode ainda estar processando os arquivos.'}${result.failed?` ${result.failed} documento(s) não importado(s) — veja a situação abaixo.`:''}`:'Operação concluída.');
    await load();
  }catch(err){setError((err as Error).message);}finally{setBusy('');}};
  const latest=data?.summaries?.find((row:any)=>row.id===selectedId);
  const pricing=data?.summary_ai_pricing;
  const field=(key:string,label:string,multiline=false)=><label className="block text-sm font-bold text-brand-text">{label}<textarea rows={multiline?4:2} value={Array.isArray(draft[key])?draft[key].join('\n'):(draft[key]||'')} onChange={event=>setDraft({...draft,[key]:Array.isArray(draft[key])?event.target.value.split('\n'):event.target.value})} className="mt-1 w-full rounded-xl border border-brand-border bg-brand-surface px-3 py-2 text-sm font-normal text-brand-text"/></label>;
  return <section className="space-y-4 rounded-2xl border border-brand-border bg-brand-surface p-4 sm:p-5">
    <div className="flex items-center justify-between gap-3"><h3 className="font-bold text-brand-text">Documentação pedagógica da aula</h3><button type="button" disabled={!!busy} onClick={()=>void load()} aria-label="Atualizar documentos da aula" className="rounded-lg border border-brand-border p-2 text-brand-text">{busy?<Loader2 size={16} className="animate-spin"/>:<RefreshCw size={16}/>}</button></div>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {message&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}
    {data&&<>
      {!data.session.documentation_consent&&<p className="text-sm text-amber-800">A documentação desta aula ainda não foi autorizada pela escola. Registre o aviso e a autorização aplicáveis antes de ativar a captura.</p>}
      <div className="flex flex-wrap items-center gap-3">
        {data.room?.state==='READY'?<a href={data.room.meeting_uri} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Entrar na sala oficial <ExternalLink size={14}/></a>:<button type="button" disabled={!!busy||!data.enabled||!data.session.documentation_consent} onClick={()=>void run('create_session_room')} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">{data.room?.state==='FAILED'?'Tentar criar a sala de novo':data.room?.space_name?'Concluir configuração da sala':'Criar sala oficial com coanfitrião'}</button>}
        <button type="button" disabled={!!busy||!data.enabled||data.room?.state!=='READY'||!data.session.documentation_consent} onClick={()=>void run('sync_artifacts')} className="rounded-xl border border-brand-border px-4 py-2 text-sm font-bold text-brand-text disabled:opacity-40">Importar transcrição e notas</button>
      </div>
      {!data.enabled&&<p className="text-sm text-brand-muted">A conexão Google está desativada ou aguardando configuração. O histórico disponível continua acessível.</p>}
      {data.room?.state==='FAILED'&&<p className="text-sm text-amber-800">O Google não criou a sala ({googleMeetIssueText(data.room.last_error_code)}). {data.room.next_attempt_at?`Nova tentativa automática às ${new Date(data.room.next_attempt_at).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'})}.`:'As tentativas automáticas acabaram; use o botão para tentar de novo.'} Enquanto isso, a aula usa o link de sempre.</p>}
      {data.room?.state==='NEEDS_RECONCILIATION'&&<p className="text-sm text-amber-800">Esta aula ficou com dois links de sala. A direção precisa escolher qual vale; enquanto isso, a aula usa o link de sempre.</p>}
      {data.room?.state==='READY'&&data.room?.last_error_code&&<p className="text-sm text-amber-800">Documentação aguardando importação ou revisão da integração. A ausência de arquivo não comprova falta ou atraso.</p>}
      {data.imports?.length>0&&<div className="rounded-xl border border-brand-border p-3"><p className="text-sm font-bold text-brand-text">Situação dos documentos{data.room?.sync_status==='COMPLETE'?' · importação concluída':data.room?.sync_status==='EXPIRED'?' · importação encerrada (7 dias depois da aula)':''}</p><ul className="mt-2 space-y-1 text-sm">{data.imports.map((row:MeetArtifactImport)=><li key={row.provider_name} className={row.status==='FAILED'?'text-amber-800':'text-brand-muted'}><span className="font-semibold text-brand-text">{row.kind==='SMART_NOTES'?'Notas do Gemini':'Transcrição'}:</span> {describeArtifactImport(row)}</li>)}</ul></div>}
      {data.artifacts.length>0&&<details className="rounded-xl border border-brand-border p-3"><summary className="cursor-pointer text-sm font-bold text-brand-text">Fontes importadas ({data.artifacts.length})</summary><div className="mt-3 space-y-3">{data.artifacts.map((artifact:any)=><details key={artifact.id} className="rounded-lg bg-brand-surface-2 p-3"><summary className="cursor-pointer text-xs font-bold text-brand-text">{artifact.kind==='SMART_NOTES'?'Notas Gemini':artifact.source==='MEET_ENTRIES'?'Transcrição (pelas falas da reunião)':'Transcrição'} · {new Date(artifact.imported_at).toLocaleString('pt-BR')}</summary><p className="mt-2 text-xs text-brand-muted">Revisão de origem preservada. Expiração prevista: {new Date(artifact.expires_at).toLocaleDateString('pt-BR')}.</p><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap text-xs text-brand-text">{artifact.source_text}</pre></details>)}</div></details>}
      {data.summary_ai_enabled&&data.artifacts.length>0&&<div className="space-y-3 rounded-xl bg-indigo-50 p-4 text-sm text-indigo-950"><p>Estruturar objetivo, prática, dificuldades e próximos passos com {data.summary_ai_model}.</p><p>{pricing?`Estimativa: US$ ${Number(pricing.estimated_usd).toFixed(4)} (entrada aproximada e até ${pricing.max_output_tokens} tokens de saída). O custo real pode variar.`:'Preço do modelo ainda não cadastrado. A geração ficará indisponível até a configuração.'}</p><label className="flex items-start gap-2"><input type="checkbox" checked={acceptApi} onChange={event=>setAcceptApi(event.target.checked)} disabled={!pricing} className="mt-1"/>Solicitar análise adicional pela API Gemini, com cobrança separada da assinatura Google.</label><button type="button" disabled={!!busy||!acceptApi||!pricing||!data.enabled} onClick={()=>void run('generate_summary',{acceptApiUsage:true})} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white disabled:opacity-40"><Sparkles size={15}/>Gerar rascunho estruturado</button></div>}
      {data.summaries.length>0&&<label className="block text-sm font-bold text-brand-text">Versão<select value={selectedId} onChange={event=>{const row=data.summaries.find((summary:any)=>summary.id===event.target.value);setSelectedId(row.id);setDraft(row.content);}} className="ml-3 rounded-lg border border-brand-border bg-brand-surface p-2 text-sm">{data.summaries.map((summary:any)=><option key={summary.id} value={summary.id}>v{summary.version} · {summary.status==='VERIFIED'?'Aprovada':summary.status==='REJECTED'?'Rejeitada':'Rascunho'} · {summary.origin==='HUMAN_REVIEW'?'Revisão humana':summary.origin==='GEMINI_API'?'IA estruturada':'Notas nativas'}</option>)}</select></label>}
      {draft?<div className="space-y-3"><p className="text-xs text-brand-muted">Revise o que foi efetivamente trabalhado. Alterações e aprovação criam uma nova versão, preservando a anterior e as fontes.</p>{field('narrative','Resumo da aula',true)}<div className="grid gap-3 sm:grid-cols-2">{field('lesson_objective','Objetivo trabalhado')}{field('content_practiced','Conteúdos praticados (um por linha)')}{field('recurring_errors','Dificuldades observadas (uma por linha)')}{field('strengths_observed','Evoluções observadas (uma por linha)')}{field('homework_assigned','Tarefa combinada')}{field('recommended_next_step','Próximo passo')}</div>
        {draft.uncertainties?.length>0&&<div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><p className="font-bold">Pontos a verificar</p><ul className="mt-1 list-disc pl-5">{draft.uncertainties.map((item:string,index:number)=><li key={index}>{item}</li>)}</ul></div>}
        {draft.evidence?.length>0&&<details><summary className="cursor-pointer text-sm font-bold text-brand-text">Trechos que sustentam o rascunho</summary>{draft.evidence.map((item:any,index:number)=><blockquote key={index} className="mt-2 border-l-2 border-indigo-300 pl-3 text-sm text-brand-muted">{item.quote}</blockquote>)}</details>}
        <label className="block text-sm font-bold text-brand-text">Nota da revisão<input value={reason} onChange={event=>setReason(event.target.value)} placeholder="Complementos ou motivo da correção" className="mt-1 w-full rounded-xl border border-brand-border bg-brand-surface px-3 py-2 font-normal"/></label>
        <div className="flex flex-wrap gap-3"><button type="button" disabled={!!busy||!draft.lesson_objective?.trim()||!draft.recommended_next_step?.trim()} onClick={()=>void run('review_summary',{parentVersionId:latest.id,status:'VERIFIED',content:draft,reason})} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Aprovar e atualizar memória do aluno</button><button type="button" disabled={!!busy} onClick={()=>void run('review_summary',{parentVersionId:latest.id,status:'REJECTED',content:draft,reason})} className="rounded-xl border border-brand-border px-4 py-2 text-sm font-bold text-brand-text">Registrar rejeição</button></div>
      </div>:<p className="text-sm text-brand-muted">Ainda não há resumo importado. As notas do Gemini aparecerão como rascunho assim que os documentos estiverem disponíveis.</p>}
    </>}
  </section>;
}
