-- Invariantes do caixa e da conciliacao Asaas.
--
-- Esta migration consolida uma unica regra para qualquer escritor
-- (webhook, tela, RPC ou reconciliador):
--   * CONFIRMED nao e caixa;
--   * RECEIVED / RECEIVED_IN_CASH sao caixa;
--   * NAO_RECEITA continua sendo dinheiro que entrou, mas em categoria
--     nao operacional;
--   * existe no maximo uma ENTRADA bruta por student_payment;
--   * cada estorno concluido e uma SAIDA separada, identificada pelo evento;
--   * credited_at, quando informado pelo Asaas, e a data efetiva do caixa;
--   * flags nunca sao fonte da verdade: sao derivadas da existencia da linha.

set local lock_timeout = '10s';
set local statement_timeout = '120s';

-- -------------------------------------------------------------------------
-- 1. Rastro antes de qualquer correcao historica
-- -------------------------------------------------------------------------

create table if not exists public.financial_ledger_migration_audit (
  id bigint generated by default as identity primary key,
  migration_key text not null,
  action text not null,
  student_payment_id uuid,
  financial_transaction_id uuid,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  constraint financial_ledger_migration_audit_once
    unique nulls not distinct (
      migration_key,
      action,
      student_payment_id,
      financial_transaction_id
    )
);

comment on table public.financial_ledger_migration_audit is
  'Snapshot imutavel das linhas alteradas por migrations do caixa. Nao e fonte de leitura do produto.';

alter table public.financial_ledger_migration_audit enable row level security;
revoke all on table public.financial_ledger_migration_audit from public, anon, authenticated;
revoke all on sequence public.financial_ledger_migration_audit_id_seq from public, anon, authenticated;
grant select on table public.financial_ledger_migration_audit to service_role;

-- -------------------------------------------------------------------------
-- 2. Datas de credito e estorno acumulado sem destruir o valor bruto
-- -------------------------------------------------------------------------

alter table public.student_payments
  add column if not exists credited_at timestamptz,
  add column if not exists refunded_amount numeric(12,2) not null default 0,
  -- A migration duravel imediatamente posterior tambem declara estas colunas
  -- com IF NOT EXISTS. Elas precisam existir aqui porque o mesmo UPDATE que
  -- avanca o estorno carrega o ID/data reais do evento para o trigger do caixa.
  add column if not exists last_provider_event_id text,
  add column if not exists last_provider_event_at timestamptz;

comment on column public.student_payments.credited_at is
  'Instante em que o valor ficou disponivel no saldo Asaas (creditDate). NULL significa que o provedor ainda nao informou.';
comment on column public.student_payments.refunded_amount is
  'Valor acumulado estornado pelo Asaas. O value e a ENTRADA permanecem brutos; cada incremento confirmado gera uma SAIDA propria.';
comment on column public.student_payments.last_provider_event_id is
  'ID estavel do ultimo evento aplicado. Em estorno, e a chave idempotente da SAIDA correspondente.';
comment on column public.student_payments.last_provider_event_at is
  'Instante declarado pelo provedor para o ultimo evento aplicado; nunca e sintetizado pelo ledger.';

do $constraints$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'public.student_payments'::regclass
       and conname = 'student_payments_refunded_amount_valid'
  ) then
    alter table public.student_payments
      add constraint student_payments_refunded_amount_valid
      check (
        refunded_amount >= 0
        and (
          (value is null and refunded_amount = 0)
          or (value is not null and refunded_amount <= value)
        )
      ) not valid;
  end if;
end
$constraints$;

alter table public.student_payments
  validate constraint student_payments_refunded_amount_valid;

-- As colunas em centavos dos pagamentos existiam, mas estavam nulas em todo o
-- historico. `value` e a fonte canonica para o backfill; depois disso o trigger
-- aceita escrita por qualquer um dos dois formatos sem permitir divergencia.
insert into public.financial_ledger_migration_audit (
  migration_key, action, student_payment_id, snapshot
)
select
  '20260825150734',
  'BACKFILL_STUDENT_AMOUNT_CENTS',
  sp.id,
  jsonb_build_object(
    'value', sp.value,
    'amount_cents', sp.amount_cents,
    'status', sp.status,
    'tenant_id', sp.tenant_id
  )
from public.student_payments sp
where sp.value is not null
  and sp.amount_cents is distinct from round(sp.value * 100)::integer
on conflict on constraint financial_ledger_migration_audit_once do nothing;

update public.student_payments
   set amount_cents = round(value * 100)::integer
 where value is not null
   and amount_cents is distinct from round(value * 100)::integer;

create or replace function public.sync_student_payment_amounts()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  v_value_changed boolean;
  v_cents_changed boolean;
begin
  if tg_op = 'INSERT' then
    if new.value is null and new.amount_cents is not null then
      new.value := new.amount_cents / 100.0;
    elsif new.value is not null and new.amount_cents is null then
      new.amount_cents := round(new.value * 100)::integer;
    elsif new.value is not null
          and new.amount_cents is not null
          and new.amount_cents <> round(new.value * 100)::integer then
      raise exception using
        errcode = '23514',
        message = 'student_payment_amount_mismatch';
    end if;
  else
    v_value_changed := new.value is distinct from old.value;
    v_cents_changed := new.amount_cents is distinct from old.amount_cents;

    if v_value_changed and not v_cents_changed then
      new.amount_cents := case
        when new.value is null then null
        else round(new.value * 100)::integer
      end;
    elsif v_cents_changed and not v_value_changed then
      new.value := case
        when new.amount_cents is null then null
        else new.amount_cents / 100.0
      end;
    elsif v_value_changed and v_cents_changed
          and not (
            new.value is null and new.amount_cents is null
          )
          and (
            new.value is null
            or new.amount_cents is null
            or new.amount_cents <> round(new.value * 100)::integer
          ) then
      raise exception using
        errcode = '23514',
        message = 'student_payment_amount_mismatch';
    end if;
  end if;

  return new;
end;
$function$;

alter function public.sync_student_payment_amounts() owner to postgres;

drop trigger if exists trg_sync_student_payment_amounts on public.student_payments;
create trigger trg_sync_student_payment_amounts
  before insert or update of value, amount_cents
  on public.student_payments
  for each row execute function public.sync_student_payment_amounts();

do $constraints$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'public.student_payments'::regclass
       and conname = 'student_payments_amount_equivalence'
  ) then
    alter table public.student_payments
      add constraint student_payments_amount_equivalence
      check (
        (value is null and amount_cents is null)
        or (
          value is not null
          and amount_cents is not null
          and amount_cents = round(value * 100)::integer
        )
      ) not valid;
  end if;
end
$constraints$;

alter table public.student_payments
  validate constraint student_payments_amount_equivalence;

-- paid_at passa a significar a data efetiva usada pelo caixa. CONFIRMED nao
-- preenche mais este campo. Em RECEIVED, creditDate vence todas as estimativas.
create or replace function public.set_student_payment_paid_at()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  v_cash_now boolean;
  v_cash_before boolean;
begin
  v_cash_now := new.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA');
  v_cash_before := tg_op = 'UPDATE'
                   and old.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA');

  if new.status = 'CONFIRMED' then
    new.paid_at := null;
  elsif v_cash_now then
    if new.credited_at is not null then
      new.paid_at := new.credited_at;
    elsif new.paid_at is null
          or not v_cash_before
          or (
            tg_op = 'UPDATE'
            and (
              old.payment_date is distinct from new.payment_date
              or old.due_date is distinct from new.due_date
            )
          ) then
      new.paid_at := coalesce(
        new.payment_date + interval '12 hours',
        new.due_date + interval '12 hours',
        now()
      );
    end if;
  end if;

  return new;
end;
$function$;

alter function public.set_student_payment_paid_at() owner to postgres;

drop trigger if exists trg_student_payment_paid_at on public.student_payments;
create trigger trg_student_payment_paid_at
  before insert or update of status, credited_at, paid_at, payment_date, due_date
  on public.student_payments
  for each row execute function public.set_student_payment_paid_at();

-- -------------------------------------------------------------------------
-- 3. Quantias do ledger sempre equivalentes, inclusive em UPDATE
-- -------------------------------------------------------------------------

insert into public.financial_ledger_migration_audit (
  migration_key, action, financial_transaction_id, student_payment_id, snapshot
)
select
  '20260825150734',
  'NORMALIZE_LEDGER_AMOUNT',
  ft.id,
  ft.student_payment_id,
  to_jsonb(ft)
from public.financial_transactions ft
where ft.amount_cents is distinct from round(ft.amount * 100)::integer
on conflict on constraint financial_ledger_migration_audit_once do nothing;

update public.financial_transactions
   set amount_cents = round(amount * 100)::integer
 where amount_cents is distinct from round(amount * 100)::integer;

create or replace function public.sync_financial_transaction_amounts()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  v_amount_changed boolean;
  v_cents_changed boolean;
begin
  if tg_op = 'INSERT' then
    if new.amount is null and new.amount_cents is not null then
      new.amount := new.amount_cents / 100.0;
    elsif new.amount is not null and new.amount_cents is null then
      new.amount_cents := round(new.amount * 100)::integer;
    elsif new.amount is not null
          and new.amount_cents is not null
          and new.amount_cents <> round(new.amount * 100)::integer then
      raise exception using
        errcode = '23514',
        message = 'financial_transaction_amount_mismatch';
    end if;
  else
    v_amount_changed := new.amount is distinct from old.amount;
    v_cents_changed := new.amount_cents is distinct from old.amount_cents;

    if v_amount_changed and not v_cents_changed then
      new.amount_cents := case
        when new.amount is null then null
        else round(new.amount * 100)::integer
      end;
    elsif v_cents_changed and not v_amount_changed then
      new.amount := case
        when new.amount_cents is null then null
        else new.amount_cents / 100.0
      end;
    elsif v_amount_changed and v_cents_changed
          and (
            new.amount is null
            or new.amount_cents is null
            or new.amount_cents <> round(new.amount * 100)::integer
          ) then
      raise exception using
        errcode = '23514',
        message = 'financial_transaction_amount_mismatch';
    elsif new.amount is not null
          and new.amount_cents is not null
          and new.amount_cents <> round(new.amount * 100)::integer then
      raise exception using
        errcode = '23514',
        message = 'financial_transaction_amount_mismatch';
    end if;
  end if;

  return new;
end;
$function$;

alter function public.sync_financial_transaction_amounts() owner to postgres;

drop trigger if exists trg_sync_financial_amounts on public.financial_transactions;
create trigger trg_sync_financial_amounts
  before insert or update of amount, amount_cents
  on public.financial_transactions
  for each row execute function public.sync_financial_transaction_amounts();

do $constraints$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'public.financial_transactions'::regclass
       and conname = 'financial_transactions_amount_equivalence'
  ) then
    alter table public.financial_transactions
      add constraint financial_transactions_amount_equivalence
      check (amount_cents = round(amount * 100)::integer) not valid;
  end if;
end
$constraints$;

alter table public.financial_transactions
  validate constraint financial_transactions_amount_equivalence;

insert into public.financial_ledger_migration_audit (
  migration_key, action, financial_transaction_id, student_payment_id, snapshot
)
select
  '20260825150734',
  'BACKFILL_OCCURRED_AT',
  ft.id,
  ft.student_payment_id,
  to_jsonb(ft)
from public.financial_transactions ft
where ft.occurred_at is null
on conflict on constraint financial_ledger_migration_audit_once do nothing;

update public.financial_transactions
   set occurred_at = coalesce(created_at, now())
 where occurred_at is null;

alter table public.financial_transactions
  alter column occurred_at set default now(),
  alter column occurred_at set not null;

-- A ENTRADA continua ligada por student_payment_id. Estornos usam uma coluna
-- separada para que o historico bruto nao seja sobrescrito e para permitir
-- multiplos eventos de devolucao do mesmo pagamento.
alter table public.financial_transactions
  add column if not exists refund_student_payment_id uuid,
  add column if not exists provider_event_id text;

do $refund_constraints$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'public.financial_transactions'::regclass
       and conname = 'financial_transactions_refund_payment_fkey'
  ) then
    alter table public.financial_transactions
      add constraint financial_transactions_refund_payment_fkey
      foreign key (refund_student_payment_id)
      references public.student_payments(id)
      on delete restrict
      not valid;
  end if;

  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'public.financial_transactions'::regclass
       and conname = 'financial_transactions_refund_shape'
  ) then
    alter table public.financial_transactions
      add constraint financial_transactions_refund_shape
      check (
        refund_student_payment_id is null
        or (
          student_payment_id is null
          and type = 'SAIDA'
          and category in ('ESTORNO_MENSALIDADE', 'estorno_aporte_ou_movimentacao')
          and amount > 0
          and provider_event_id is not null
          and length(trim(provider_event_id)) between 1 and 240
        )
      ) not valid;
  end if;
end
$refund_constraints$;

alter table public.financial_transactions
  validate constraint financial_transactions_refund_payment_fkey,
  validate constraint financial_transactions_refund_shape;

comment on column public.financial_transactions.refund_student_payment_id is
  'Pagamento cuja entrada bruta foi parcialmente ou integralmente estornada por esta SAIDA.';
comment on column public.financial_transactions.provider_event_id is
  'ID duravel do evento Asaas que originou o estorno; chave de idempotencia, sem data sintetica.';

-- -------------------------------------------------------------------------
-- 4. Idempotencia estrutural: uma linha de caixa por pagamento
-- -------------------------------------------------------------------------

do $duplicates$
declare
  v_duplicates integer;
begin
  select count(*)
    into v_duplicates
    from (
      select ft.student_payment_id
        from public.financial_transactions ft
       where ft.student_payment_id is not null
       group by ft.student_payment_id
      having count(*) > 1
    ) duplicated;

  if v_duplicates > 0 then
    raise exception using
      errcode = '23505',
      message = format(
        'financial_ledger_duplicate_student_payments:%s; migration aborted without deleting history',
        v_duplicates
      );
  end if;
end
$duplicates$;

create unique index if not exists uq_financial_transactions_student_payment
  on public.financial_transactions (student_payment_id)
  where student_payment_id is not null;

create unique index if not exists uq_financial_transactions_refund_event
  on public.financial_transactions (provider_event_id)
  where refund_student_payment_id is not null
    and provider_event_id is not null;

create index if not exists financial_transactions_refund_payment_occurred_idx
  on public.financial_transactions (refund_student_payment_id, occurred_at)
  where refund_student_payment_id is not null;

do $index_postcondition$
begin
  if not exists (
    select 1
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      join pg_index i on i.indexrelid = c.oid
     where n.nspname = 'public'
       and c.relname = 'uq_financial_transactions_student_payment'
       and i.indisunique
       and i.indrelid = 'public.financial_transactions'::regclass
       and i.indnkeyatts = 1
       and i.indkey[0] = (
         select a.attnum
           from pg_attribute a
          where a.attrelid = 'public.financial_transactions'::regclass
            and a.attname = 'student_payment_id'
            and not a.attisdropped
       )
       and i.indpred is not null
       and pg_get_expr(i.indpred, i.indrelid) = '(student_payment_id IS NOT NULL)'
  ) then
    raise exception 'uq_financial_transactions_student_payment is absent or not a partial unique index';
  end if;
end
$index_postcondition$;

do $refund_index_postcondition$
begin
  if not exists (
    select 1
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      join pg_index i on i.indexrelid = c.oid
     where n.nspname = 'public'
       and c.relname = 'uq_financial_transactions_refund_event'
       and i.indisunique
       and i.indrelid = 'public.financial_transactions'::regclass
       and i.indnkeyatts = 1
       and i.indkey[0] = (
         select a.attnum
           from pg_attribute a
          where a.attrelid = 'public.financial_transactions'::regclass
            and a.attname = 'provider_event_id'
            and not a.attisdropped
       )
       and i.indpred is not null
       and pg_get_expr(i.indpred, i.indrelid) =
         '((refund_student_payment_id IS NOT NULL) AND (provider_event_id IS NOT NULL))'
  ) then
    raise exception 'uq_financial_transactions_refund_event is absent or not the expected partial unique index';
  end if;
end
$refund_index_postcondition$;

-- O rateio/notificacao acompanha dinheiro efetivamente disponibilizado. A
-- confirmacao ainda pode ser estornada antes do credito e nao pode disparar
-- uma automacao financeira antecipada.
create or replace function public.notify_payment_split()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_service_key text;
  v_request_id bigint;
begin
  if new.status not in ('RECEIVED', 'RECEIVED_IN_CASH')
     or coalesce(new.value, 0) <= 0
  then
    return new;
  end if;

  if tg_op = 'UPDATE' and old.status is not distinct from new.status then
    return new;
  end if;

  if not exists (
    select 1
      from public.payment_split_settings as setting
     where setting.tenant_id = new.tenant_id
       and setting.is_active
  ) then
    return new;
  end if;

  select secret.decrypted_secret
    into v_service_key
    from vault.decrypted_secrets as secret
   where secret.name = 'wisewolf_service_role_key'
   limit 1;
  if nullif(v_service_key, '') is null then
    raise warning 'notify_payment_split: service key ausente';
    return new;
  end if;

  select net.http_post(
    url := 'http://kong:8000/functions/v1/payment-split-notify',
    headers := pg_catalog.jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || v_service_key
    ),
    body := pg_catalog.jsonb_build_object('payment_id', new.id),
    timeout_milliseconds := 20000
  ) into v_request_id;

  return new;
exception when others then
  raise warning 'notify_payment_split falhou (pagamento preservado): %', sqlerrm;
  return new;
end;
$function$;

alter function public.notify_payment_split() owner to postgres;
revoke all on function public.notify_payment_split()
  from public, anon, authenticated, service_role;

-- -------------------------------------------------------------------------
-- 5. Um unico trigger mantem caixa, categoria, data, estorno e flag
-- -------------------------------------------------------------------------

create or replace function public.ledger_on_payment_received()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_receipt_should_exist boolean;
  v_receipt_existed boolean;
  v_cash_before boolean;
  v_relevant_change boolean;
  v_category text;
  v_refund_category text;
  v_gross_amount numeric;
  v_refund_delta numeric := 0;
  v_refund_event_fresh boolean := false;
  v_occurred_at timestamptz;
  v_existing_occurred_at timestamptz;
  v_removed_amount numeric;
  v_removed_count integer := 0;
  v_refund_inserted integer := 0;
  v_has_ledger boolean;
  v_existing_refund record;
  v_paid_teacher_closings jsonb;
  v_payment_competence text;
begin
  select exists (
           select 1
             from public.financial_transactions ft
            where ft.student_payment_id = new.id
         ),
         (
           select ft.occurred_at
             from public.financial_transactions ft
            where ft.student_payment_id = new.id
         )
    into v_receipt_existed, v_existing_occurred_at;

  v_cash_before := tg_op = 'UPDATE'
                   and (
                     old.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
                     or v_receipt_existed
                   );
  v_receipt_should_exist :=
    new.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
    or (
      new.status = 'REFUNDED'
      and (new.credited_at is not null or v_receipt_existed)
    );

  if tg_op = 'UPDATE'
     and coalesce(new.refunded_amount, 0) < coalesce(old.refunded_amount, 0) then
    raise exception using
      errcode = '23514',
      message = 'student_payment_refunded_amount_regression';
  end if;

  v_relevant_change := tg_op = 'INSERT'
    or old.status is distinct from new.status
    or old.tenant_id is distinct from new.tenant_id
    or old.student_id is distinct from new.student_id
    or old.value is distinct from new.value
    or old.refunded_amount is distinct from new.refunded_amount
    or old.credited_at is distinct from new.credited_at
    or old.last_provider_event_id is distinct from new.last_provider_event_id
    or old.last_provider_event_at is distinct from new.last_provider_event_at
    or old.paid_at is distinct from new.paid_at
    or old.payment_date is distinct from new.payment_date
    or old.due_date is distinct from new.due_date;

  -- Atualizacao recursiva feita abaixo apenas para espelhar a flag. Se nenhum
  -- campo contabil mudou, limita-se a restaurar a flag derivada.
  if not v_relevant_change then
    select exists (
      select 1
        from public.financial_transactions ft
       where ft.student_payment_id = new.id
    ) into v_has_ledger;

    if new.ledger_entry_created is distinct from v_has_ledger then
      update public.student_payments sp
         set ledger_entry_created = v_has_ledger
       where sp.id = new.id
         and sp.ledger_entry_created is distinct from v_has_ledger;
    end if;
    return new;
  end if;

  v_category := case
    when new.status = 'NAO_RECEITA' then 'aporte_ou_movimentacao'
    else 'MENSALIDADE'
  end;
  v_refund_category := case
    when new.status = 'NAO_RECEITA' then 'estorno_aporte_ou_movimentacao'
    else 'ESTORNO_MENSALIDADE'
  end;
  v_gross_amount := round(coalesce(new.value, 0), 2);
  v_occurred_at := coalesce(
    new.credited_at,
    new.paid_at,
    new.payment_date + interval '12 hours',
    new.due_date + interval '12 hours',
    v_existing_occurred_at,
    now()
  );

  -- O recebimento e imutavelmente bruto. Um estorno nunca reduz nem apaga esta
  -- linha: sua contrapartida vive em uma SAIDA datada pelo evento do provedor.
  if v_receipt_should_exist
     and new.tenant_id is not null
     and v_gross_amount > 0 then
    insert into public.financial_transactions (
      tenant_id,
      type,
      category,
      amount,
      amount_cents,
      student_payment_id,
      reference_id,
      occurred_at,
      description,
      created_at
    ) values (
      new.tenant_id,
      'ENTRADA',
      v_category,
      v_gross_amount,
      round(v_gross_amount * 100)::integer,
      new.id,
      new.student_id,
      v_occurred_at,
      case
        when new.status = 'NAO_RECEITA' then 'Movimentacao nao operacional (conciliacao automatica)'
        else 'Mensalidade (conciliacao automatica)'
      end,
      now()
    )
    on conflict (student_payment_id) where student_payment_id is not null
    do update set
      tenant_id = excluded.tenant_id,
      type = excluded.type,
      category = excluded.category,
      amount = excluded.amount,
      amount_cents = excluded.amount_cents,
      reference_id = excluded.reference_id,
      occurred_at = excluded.occurred_at,
      description = excluded.description;
  elsif new.status = 'REFUNDED' and v_receipt_existed then
    -- Nao destrua a entrada historica se a atualizacao de identidade/valor
    -- estiver incompleta. A divergencia fica explicita para conciliacao.
    insert into public.reconciliation_issues (
      tenant_id, kind, student_payment_id, details
    ) values (
      coalesce(new.tenant_id, 'master'),
      'REFUNDED_PAYMENT_RECEIPT_DATA_INVALID',
      new.id,
      jsonb_build_object(
        'status_novo', new.status,
        'tenant_id', new.tenant_id,
        'valor_bruto', new.value,
        'entrada_preservada', true,
        'registrado_em', now()
      )
    );
  else
    select ft.amount
      into v_removed_amount
      from public.financial_transactions ft
     where ft.student_payment_id = new.id
     for update;

    delete from public.financial_transactions ft
     where ft.student_payment_id = new.id;
    get diagnostics v_removed_count = row_count;

    if v_removed_count > 0 and v_cash_before then
      insert into public.reconciliation_issues (
        tenant_id,
        kind,
        student_payment_id,
        details
      ) values (
        coalesce(new.tenant_id, old.tenant_id, 'master'),
        case when new.tenant_id is null
          then 'PAYMENT_WITHOUT_TENANT'
          else 'PAYMENT_REVERSED'
        end,
        new.id,
        jsonb_build_object(
          'status_anterior', case when tg_op = 'UPDATE' then old.status else null end,
          'status_novo', new.status,
          'valor_bruto', new.value,
          'valor_estornado', new.refunded_amount,
          'valor_removido_do_caixa', v_removed_amount,
          'removido_em', now()
        )
      );
    end if;
  end if;

  -- Mudanca deliberada RECEIVED <-> NAO_RECEITA recategoriza tambem eventuais
  -- estornos, sem tocar em valor, ID ou data historica do evento.
  if new.tenant_id is not null then
    update public.financial_transactions ft
       set tenant_id = new.tenant_id,
           category = v_refund_category,
           reference_id = new.student_id,
           description = case
             when new.status = 'NAO_RECEITA'
               then 'Estorno de movimentacao nao operacional (evento Asaas)'
             else 'Estorno de mensalidade (evento Asaas)'
           end
     where ft.refund_student_payment_id = new.id
       and (
         ft.tenant_id is distinct from new.tenant_id
         or ft.category is distinct from v_refund_category
         or ft.reference_id is distinct from new.student_id
       );
  end if;

  -- Gate obrigatorio: um estorno so e SAIDA se houve ENTRADA comprovada.
  select exists (
    select 1
      from public.financial_transactions ft
     where ft.student_payment_id = new.id
  ) into v_has_ledger;

  if tg_op = 'INSERT' then
    v_refund_delta := round(coalesce(new.refunded_amount, 0), 2);
    v_refund_event_fresh := new.last_provider_event_id is not null
      and length(trim(new.last_provider_event_id)) between 1 and 240
      and new.last_provider_event_at is not null;
  else
    v_refund_delta := round(
      coalesce(new.refunded_amount, 0) - coalesce(old.refunded_amount, 0),
      2
    );
    v_refund_event_fresh := new.last_provider_event_id is not null
      and length(trim(new.last_provider_event_id)) between 1 and 240
      and new.last_provider_event_at is not null
      and (
        new.last_provider_event_id is distinct from old.last_provider_event_id
        or new.last_provider_event_at is distinct from old.last_provider_event_at
      );
  end if;

  if v_refund_delta > 0 and not v_has_ledger then
    -- Estorno anterior ao credito (por exemplo CONFIRMED -> REFUNDED) nao e
    -- saida de caixa: nenhum saldo havia sido disponibilizado. A issue abaixo
    -- guarda a explicacao, mas nenhuma movimentacao e sintetizada.
    null;
  elsif v_refund_delta > 0
        and v_refund_event_fresh
        and new.tenant_id is not null then
    insert into public.financial_transactions (
      tenant_id,
      type,
      category,
      amount,
      amount_cents,
      refund_student_payment_id,
      provider_event_id,
      reference_id,
      occurred_at,
      description,
      created_at
    ) values (
      new.tenant_id,
      'SAIDA',
      v_refund_category,
      v_refund_delta,
      round(v_refund_delta * 100)::integer,
      new.id,
      trim(new.last_provider_event_id),
      new.student_id,
      new.last_provider_event_at,
      case
        when new.status = 'NAO_RECEITA' then 'Estorno de movimentacao nao operacional (evento Asaas)'
        else 'Estorno de mensalidade (evento Asaas)'
      end,
      now()
    )
    on conflict (provider_event_id)
      where refund_student_payment_id is not null
        and provider_event_id is not null
    do nothing;
    get diagnostics v_refund_inserted = row_count;

    -- ON CONFLICT garante retry idempotente. Esta verificacao impede que um ID
    -- do provedor reutilizado ou um retry divergente seja aceito em silencio.
    select
      ft.refund_student_payment_id,
      ft.tenant_id,
      ft.type,
      ft.category,
      ft.amount,
      ft.occurred_at
      into v_existing_refund
      from public.financial_transactions ft
     where ft.refund_student_payment_id is not null
       and ft.provider_event_id = trim(new.last_provider_event_id);

    if not found
       or v_existing_refund.refund_student_payment_id is distinct from new.id
       or v_existing_refund.tenant_id is distinct from new.tenant_id
       or v_existing_refund.type is distinct from 'SAIDA'
       or v_existing_refund.category is distinct from v_refund_category
       or v_existing_refund.amount is distinct from v_refund_delta
       or v_existing_refund.occurred_at is distinct from new.last_provider_event_at then
      raise exception using
        errcode = '23505',
        message = 'refund_provider_event_conflict';
    end if;
  elsif v_refund_delta > 0 then
    insert into public.reconciliation_issues (
      tenant_id,
      kind,
      student_payment_id,
      details
    ) values (
      coalesce(new.tenant_id, 'master'),
      'REFUND_LEDGER_EVENT_CONTEXT_MISSING',
      new.id,
      jsonb_build_object(
        'valor_bruto', new.value,
        'valor_estornado_anterior', case
          when tg_op = 'UPDATE' then old.refunded_amount
          else 0
        end,
        'valor_estornado_novo', new.refunded_amount,
        'delta_sem_lancamento', v_refund_delta,
        'provider_event_id', new.last_provider_event_id,
        'provider_event_at', new.last_provider_event_at,
        'contexto_evento_novo', v_refund_event_fresh,
        'tenant_id_ausente', new.tenant_id is null,
        'data_sintetizada', false,
        'registrado_em', now()
      )
    );
  end if;

  if v_refund_delta > 0
     and not exists (
       select 1
         from public.financial_transactions ft
        where ft.student_payment_id = new.id
     ) then
    insert into public.reconciliation_issues (
      tenant_id, kind, student_payment_id, details
    ) values (
      coalesce(new.tenant_id, 'master'),
      'REFUND_WITHOUT_RECEIPT_LEDGER',
      new.id,
      jsonb_build_object(
        'valor_bruto', new.value,
        'delta_estornado', v_refund_delta,
        'provider_event_id', new.last_provider_event_id,
        'provider_event_at', new.last_provider_event_at,
        'entrada_sintetizada', false,
        'motivo', 'Nao ha data de credito comprovada para reconstruir a ENTRADA historica.',
        'registrado_em', now()
      )
    );
  end if;

  if v_refund_delta > 0 then
    insert into public.reconciliation_issues (
      tenant_id,
      kind,
      student_payment_id,
      details
    ) values (
      coalesce(new.tenant_id, 'master'),
      case
        when coalesce(new.refunded_amount, 0) < coalesce(new.value, 0)
          then 'PAYMENT_PARTIALLY_REFUNDED'
        else 'PAYMENT_FULLY_REFUNDED'
      end,
      new.id,
      jsonb_build_object(
        'valor_bruto', new.value,
        'valor_estornado_anterior', case
          when tg_op = 'UPDATE' then old.refunded_amount
          else 0
        end,
        'valor_estornado_novo', new.refunded_amount,
        'delta_estornado', v_refund_delta,
        'provider_event_id', new.last_provider_event_id,
        'provider_event_at', new.last_provider_event_at,
        'saida_criada', v_refund_inserted = 1,
        'registrado_em', now()
      )
    );
  end if;

  -- Um estorno posterior ao repasse do professor exige decisao humana. A
  -- mensalidade e o fechamento nao possuem regra de rateio reverso suficiente
  -- para debitar o professor com seguranca; por isso o trigger apenas abre uma
  -- issue com os fechamentos possivelmente afetados e nunca altera o repasse.
  if v_refund_delta > 0
     and new.student_id is not null then
    v_payment_competence := to_char(
      coalesce(new.due_date, new.payment_date, new.credited_at::date),
      'YYYY-MM'
    );

    select jsonb_agg(candidate.id order by candidate.id)
      into v_paid_teacher_closings
      from (
        select distinct tc.id
          from public.teacher_closings tc
         where tc.tenant_id = new.tenant_id
           and tc.month_year = v_payment_competence
           and upper(coalesce(tc.status, '')) in ('PAGO', 'PAID', 'COMPLETED')
           and exists (
             select 1
               from public.v_payable_class_logs pcl
              where pcl.teacher_id = tc.teacher_id
                and pcl.student_id = new.student_id
                and to_char(pcl.class_date, 'YYYY-MM') = v_payment_competence
           )
      ) candidate;

    if v_paid_teacher_closings is not null then
      insert into public.reconciliation_issues (
        tenant_id,
        kind,
        student_payment_id,
        details
      ) values (
        coalesce(new.tenant_id, 'master'),
        'REFUND_REQUIRES_TEACHER_PAYOUT_REVIEW',
        new.id,
        jsonb_build_object(
          'competencia', v_payment_competence,
          'fechamentos_pagos', v_paid_teacher_closings,
          'valor_bruto', new.value,
          'valor_estornado_anterior', case
            when tg_op = 'UPDATE' then old.refunded_amount
            else 0
          end,
          'valor_estornado_novo', new.refunded_amount,
          'acao_automatica', false,
          'motivo', 'Rateio ja liquidado exige revisao; nenhum debito automatico foi criado.',
          'registrado_em', now()
        )
      );
    end if;
  end if;

  select exists (
    select 1
      from public.financial_transactions ft
     where ft.student_payment_id = new.id
  ) into v_has_ledger;

  if new.ledger_entry_created is distinct from v_has_ledger then
    update public.student_payments sp
       set ledger_entry_created = v_has_ledger
     where sp.id = new.id
       and sp.ledger_entry_created is distinct from v_has_ledger;
  end if;

  return new;
end;
$function$;

alter function public.ledger_on_payment_received() owner to postgres;

comment on function public.ledger_on_payment_received() is
  'Fonte unica do caixa de mensalidades: uma ENTRADA bruta pela data de credito e uma SAIDA por evento real de estorno; CONFIRMED nunca e caixa e NAO_RECEITA preserva a classificacao.';

revoke all on function public.ledger_on_payment_received()
  from public, anon, authenticated;

drop trigger if exists trg_ledger_on_payment on public.student_payments;
create trigger trg_ledger_on_payment
  after insert or update
  on public.student_payments
  for each row execute function public.ledger_on_payment_received();

-- -------------------------------------------------------------------------
-- 6. Convergencia segura do historico (snapshot antes de UPDATE/DELETE)
-- -------------------------------------------------------------------------

insert into public.financial_ledger_migration_audit (
  migration_key, action, financial_transaction_id, student_payment_id, snapshot
)
select
  '20260825150734',
  'REMOVE_NON_CASH_LEDGER',
  ft.id,
  ft.student_payment_id,
  jsonb_build_object(
    'financial_transaction', to_jsonb(ft),
    'student_payment', to_jsonb(sp)
  )
from public.financial_transactions ft
join public.student_payments sp on sp.id = ft.student_payment_id
where sp.status <> 'REFUNDED'
  and (
    sp.status not in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
    or sp.tenant_id is null
    or coalesce(sp.value, 0) <= 0
  )
on conflict on constraint financial_ledger_migration_audit_once do nothing;

delete from public.financial_transactions ft
using public.student_payments sp
where sp.id = ft.student_payment_id
  and sp.status <> 'REFUNDED'
  and (
      sp.status not in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
      or sp.tenant_id is null
      or coalesce(sp.value, 0) <= 0
  );

-- CONFIRMED havia herdado paid_at de payment_date. O campo agora representa
-- disponibilidade de caixa, portanto o valor antigo tambem fica no snapshot.
insert into public.financial_ledger_migration_audit (
  migration_key, action, student_payment_id, snapshot
)
select
  '20260825150734',
  'CLEAR_CONFIRMED_PAID_AT',
  sp.id,
  to_jsonb(sp)
from public.student_payments sp
where sp.status = 'CONFIRMED'
  and (sp.paid_at is not null or coalesce(sp.ledger_entry_created, false))
on conflict on constraint financial_ledger_migration_audit_once do nothing;

update public.student_payments
   set paid_at = null,
       ledger_entry_created = false
 where status = 'CONFIRMED'
   and (paid_at is not null or coalesce(ledger_entry_created, false));

insert into public.financial_ledger_migration_audit (
  migration_key, action, financial_transaction_id, student_payment_id, snapshot
)
select
  '20260825150734',
  'CANONICALIZE_PAYMENT_LEDGER',
  ft.id,
  ft.student_payment_id,
  jsonb_build_object(
    'financial_transaction', to_jsonb(ft),
    'student_payment', to_jsonb(sp)
  )
from public.financial_transactions ft
join public.student_payments sp on sp.id = ft.student_payment_id
where sp.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA', 'REFUNDED')
  and sp.tenant_id is not null
  and coalesce(sp.value, 0) > 0
  and (
    ft.tenant_id is distinct from sp.tenant_id
    or ft.type is distinct from 'ENTRADA'
    or ft.category is distinct from case
      when sp.status = 'NAO_RECEITA' then 'aporte_ou_movimentacao'
      else 'MENSALIDADE'
    end
    or ft.amount is distinct from round(sp.value, 2)
    or ft.amount_cents is distinct from round(sp.value * 100)::integer
    or ft.reference_id is distinct from sp.student_id
    or ft.occurred_at is distinct from coalesce(
      sp.credited_at,
      sp.paid_at,
      sp.payment_date + interval '12 hours',
      sp.due_date + interval '12 hours',
      ft.occurred_at
    )
  )
on conflict on constraint financial_ledger_migration_audit_once do nothing;

update public.financial_transactions ft
   set tenant_id = sp.tenant_id,
       type = 'ENTRADA',
       category = case
         when sp.status = 'NAO_RECEITA' then 'aporte_ou_movimentacao'
         else 'MENSALIDADE'
       end,
       amount = round(sp.value, 2),
       amount_cents = round(sp.value * 100)::integer,
       reference_id = sp.student_id,
       occurred_at = coalesce(
         sp.credited_at,
         sp.paid_at,
         sp.payment_date + interval '12 hours',
         sp.due_date + interval '12 hours',
         ft.occurred_at
       )
  from public.student_payments sp
 where sp.id = ft.student_payment_id
   and sp.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA', 'REFUNDED')
   and sp.tenant_id is not null
   and coalesce(sp.value, 0) > 0
   and (
     ft.tenant_id is distinct from sp.tenant_id
     or ft.type is distinct from 'ENTRADA'
     or ft.category is distinct from case
       when sp.status = 'NAO_RECEITA' then 'aporte_ou_movimentacao'
       else 'MENSALIDADE'
     end
     or ft.amount is distinct from round(sp.value, 2)
     or ft.amount_cents is distinct from round(sp.value * 100)::integer
     or ft.reference_id is distinct from sp.student_id
     or ft.occurred_at is distinct from coalesce(
       sp.credited_at,
       sp.paid_at,
       sp.payment_date + interval '12 hours',
       sp.due_date + interval '12 hours',
       ft.occurred_at
     )
   );

-- Nao existe fonte confiavel para datar estornos preexistentes: a coluna
-- acumulada nao informa quando cada devolucao saiu. Em vez de fabricar uma
-- SAIDA em created_at/now(), deixe a lacuna observavel para conciliacao.
insert into public.reconciliation_issues (
  tenant_id, kind, student_payment_id, details
)
select
  coalesce(sp.tenant_id, 'master'),
  'HISTORICAL_REFUND_EVENT_CONTEXT_MISSING',
  sp.id,
  jsonb_build_object(
    'status', sp.status,
    'valor_bruto', sp.value,
    'valor_estornado_acumulado', sp.refunded_amount,
    'soma_saidas_com_evento', coalesce(refunds.total, 0),
    'last_provider_event_id', sp.last_provider_event_id,
    'last_provider_event_at', sp.last_provider_event_at,
    'data_sintetizada', false,
    'registrado_em', now()
  )
from public.student_payments sp
left join lateral (
  select sum(ft.amount) as total
    from public.financial_transactions ft
   where ft.refund_student_payment_id = sp.id
) refunds on true
where (
    sp.status = 'REFUNDED'
    or coalesce(sp.refunded_amount, 0) > coalesce(refunds.total, 0)
  )
  and (
    sp.credited_at is not null
    or sp.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
    or exists (
      select 1
        from public.financial_transactions receipt
       where receipt.student_payment_id = sp.id
    )
  )
  and not exists (
    select 1
      from public.reconciliation_issues ri
     where ri.student_payment_id = sp.id
       and ri.kind = 'HISTORICAL_REFUND_EVENT_CONTEXT_MISSING'
       and not coalesce(ri.resolved, false)
  );

-- -------------------------------------------------------------------------
-- 7. Reconciliacao transacional, paginavel e baseada em NOT EXISTS
-- -------------------------------------------------------------------------

create or replace function public.reconcile_student_payment_ledger(
  p_limit integer default 100,
  p_after_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_payment record;
  v_limit integer;
  v_processed integer := 0;
  v_inserted integer := 0;
  v_delta integer := 0;
  v_flags_corrected integer := 0;
  v_last_id uuid := null;
  v_has_more boolean := false;
  v_lock_acquired boolean;
  v_gross_amount numeric;
begin
  v_limit := greatest(1, least(coalesce(p_limit, 100), 1000));

  select pg_try_advisory_xact_lock(
    hashtextextended('wise-wolf:reconcile-student-payment-ledger', 0)
  ) into v_lock_acquired;

  if not v_lock_acquired then
    return jsonb_build_object(
      'busy', true,
      'processed', 0,
      'inserted', 0,
      'flags_corrected', 0,
      'next_after_id', null,
      'has_more', false
    );
  end if;

  for v_payment in
    select sp.*
      from public.student_payments sp
     where (
         sp.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
         or (sp.status = 'REFUNDED' and sp.credited_at is not null)
       )
       and sp.tenant_id is not null
       and coalesce(sp.value, 0) > 0
       and (p_after_id is null or sp.id > p_after_id)
       and not exists (
         select 1
           from public.financial_transactions ft
          where ft.student_payment_id = sp.id
       )
     order by sp.id
     limit v_limit
     for update of sp
  loop
    v_processed := v_processed + 1;
    v_last_id := v_payment.id;
    v_gross_amount := round(coalesce(v_payment.value, 0), 2);

    insert into public.financial_transactions (
      tenant_id,
      type,
      category,
      amount,
      amount_cents,
      student_payment_id,
      reference_id,
      occurred_at,
      description,
      created_at
    ) values (
      v_payment.tenant_id,
      'ENTRADA',
      case
        when v_payment.status = 'NAO_RECEITA' then 'aporte_ou_movimentacao'
        else 'MENSALIDADE'
      end,
      v_gross_amount,
      round(v_gross_amount * 100)::integer,
      v_payment.id,
      v_payment.student_id,
      coalesce(
        v_payment.credited_at,
        v_payment.paid_at,
        v_payment.payment_date + interval '12 hours',
        v_payment.due_date + interval '12 hours',
        now()
      ),
      case
        when v_payment.status = 'NAO_RECEITA' then 'Movimentacao nao operacional (reconciliacao)'
        else 'Mensalidade (reconciliacao)'
      end,
      now()
    )
    on conflict (student_payment_id) where student_payment_id is not null
    do nothing;

    get diagnostics v_delta = row_count;
    v_inserted := v_inserted + v_delta;
  end loop;

  with ledger_state as (
    select
      sp.id,
      exists (
        select 1
          from public.financial_transactions ft
         where ft.student_payment_id = sp.id
      ) as has_ledger
    from public.student_payments sp
  ), corrected as (
    update public.student_payments sp
       set ledger_entry_created = ls.has_ledger
      from ledger_state ls
     where ls.id = sp.id
       and sp.ledger_entry_created is distinct from ls.has_ledger
    returning 1
  )
  select count(*) into v_flags_corrected from corrected;

  if v_last_id is not null then
    select exists (
      select 1
        from public.student_payments sp
       where (
           sp.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
           or (sp.status = 'REFUNDED' and sp.credited_at is not null)
         )
         and sp.tenant_id is not null
         and coalesce(sp.value, 0) > 0
         and sp.id > v_last_id
         and not exists (
           select 1
             from public.financial_transactions ft
            where ft.student_payment_id = sp.id
         )
    ) into v_has_more;
  end if;

  return jsonb_build_object(
    'busy', false,
    'processed', v_processed,
    'inserted', v_inserted,
    'flags_corrected', v_flags_corrected,
    'next_after_id', v_last_id,
    'has_more', v_has_more
  );
end;
$function$;

alter function public.reconcile_student_payment_ledger(integer, uuid) owner to postgres;
comment on function public.reconcile_student_payment_ledger(integer, uuid) is
  'Recria em paginas ENTRADAS brutas comprovadas sem ledger usando NOT EXISTS; nunca sintetiza SAIDAS historicas de estorno, serializa concorrencia e corrige a flag pela existencia real.';

revoke all on function public.reconcile_student_payment_ledger(integer, uuid)
  from public, anon, authenticated;
grant execute on function public.reconcile_student_payment_ledger(integer, uuid)
  to service_role;

-- Concilia todo o pequeno historico atual em lotes. O cursor torna o loop
-- limitado e o indice unico torna repeticoes/concorrrencia idempotentes.
do $reconcile_existing$
declare
  v_result jsonb;
  v_after uuid := null;
  v_iterations integer := 0;
begin
  loop
    v_iterations := v_iterations + 1;
    if v_iterations > 10000 then
      raise exception 'reconcile_student_payment_ledger exceeded safety iteration limit';
    end if;

    v_result := public.reconcile_student_payment_ledger(500, v_after);
    v_after := nullif(v_result ->> 'next_after_id', '')::uuid;

    exit when not coalesce((v_result ->> 'has_more')::boolean, false);
    if v_after is null then
      raise exception 'reconcile_student_payment_ledger returned has_more without cursor';
    end if;
  end loop;
end
$reconcile_existing$;

-- -------------------------------------------------------------------------
-- 8. Caixa por evento e DRE liquida por competencia
-- -------------------------------------------------------------------------

-- A facade publica get_cashflow(text), criada na migration de autorizacao
-- imediatamente anterior, continua intacta. Somente a implementacao owner-only
-- e atualizada. Em regime de caixa a fonte canonica e o ledger: a ENTRADA fica
-- no credito e cada SAIDA de estorno fica no mes do evento que a comprovou.
create or replace function public.get_cashflow_unchecked(
  p_month text default null::text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_tenant text;
  v_month text;
  v_month_start date;
  v_month_end date;
  v_in numeric;
  v_teacher numeric;
  v_vendor numeric;
  v_referral numeric;
  v_expense numeric;
begin
  select p.tenant_id
    into v_tenant
    from public.profiles p
   where p.id = auth.uid();

  v_month := coalesce(p_month, to_char(current_date, 'YYYY-MM'));
  if v_month !~ '^\d{4}-\d{2}$' then
    raise exception 'Mes invalido (use YYYY-MM)';
  end if;
  v_month_start := to_date(v_month || '-01', 'YYYY-MM-DD');
  if to_char(v_month_start, 'YYYY-MM') <> v_month then
    raise exception 'Mes invalido (use YYYY-MM)';
  end if;
  v_month_end := (v_month_start + interval '1 month')::date;

  select coalesce(sum(ft.amount), 0)
    into v_in
    from public.financial_transactions ft
   where ft.tenant_id = v_tenant
     and ft.type = 'ENTRADA'
     and ft.category is distinct from 'aporte_ou_movimentacao'
     and ft.occurred_at >= v_month_start
     and ft.occurred_at < v_month_end;

  select coalesce(sum(tc.total_amount), 0)
    into v_teacher
    from public.teacher_closings tc
   where tc.tenant_id = v_tenant
     and tc.status = 'PAGO'
     and coalesce(tc.paid_at, (tc.month_year || '-01')::date) >= v_month_start
     and coalesce(tc.paid_at, (tc.month_year || '-01')::date) < v_month_end;

  select coalesce(sum(vc.amount_brl), 0)
    into v_vendor
    from public.vendor_commissions vc
   where vc.tenant_id = v_tenant
     and vc.status = 'PAID'
     and vc.paid_at >= v_month_start
     and vc.paid_at < v_month_end;

  select coalesce(sum(rr.amount_brl), 0)
    into v_referral
    from public.referral_rewards rr
   where rr.tenant_id = v_tenant
     and rr.status = 'PAID'
     and rr.paid_at >= v_month_start
     and rr.paid_at < v_month_end;

  select coalesce(sum(ft.amount), 0)
    into v_expense
    from public.financial_transactions ft
   where ft.tenant_id = v_tenant
     and ft.type = 'SAIDA'
     and ft.category is distinct from 'teacher_payout'
     and ft.category is distinct from 'estorno_aporte_ou_movimentacao'
     and ft.account_code is distinct from '5.1.01'
     and ft.occurred_at >= v_month_start
     and ft.occurred_at < v_month_end;

  return jsonb_build_object(
    'month', v_month,
    'entradas', v_in,
    'saidas', jsonb_build_object(
      'professores', v_teacher,
      'vendedores', v_vendor,
      'indicacoes', v_referral,
      'despesas', v_expense,
      'total', v_teacher + v_vendor + v_referral + v_expense
    ),
    'saldo', v_in - (v_teacher + v_vendor + v_referral + v_expense),
    -- Valores ainda devidos permanecem brutos: estorno de dinheiro ja
    -- realizado nao reduz o principal de outra fatura em aberto.
    'inadimplencia', (
      select jsonb_build_object(
        'total', coalesce(sum(sp.value), 0),
        'd1_30', coalesce(sum(sp.value) filter (
          where current_date - sp.due_date between 1 and 30
        ), 0),
        'd31_60', coalesce(sum(sp.value) filter (
          where current_date - sp.due_date between 31 and 60
        ), 0),
        'd60plus', coalesce(sum(sp.value) filter (
          where current_date - sp.due_date > 60
        ), 0),
        'count', count(*)
      )
      from public.student_payments sp
      where sp.tenant_id = v_tenant
        and sp.status in ('OVERDUE', 'DUNNING_REQUESTED')
    ),
    'a_receber', (
      select coalesce(sum(sp.value), 0)
        from public.student_payments sp
       where sp.tenant_id = v_tenant
         and sp.status = 'PENDING'
         and sp.due_date >= v_month_start
         and sp.due_date < v_month_end
    ),
    'serie', (
      select jsonb_agg(
        jsonb_build_object('mes', series.month_year, 'entradas', series.amount)
        order by series.month_year
      )
      from (
        select
          to_char(months.month_start, 'YYYY-MM') as month_year,
          coalesce((
            select sum(ft.amount)
              from public.financial_transactions ft
             where ft.tenant_id = v_tenant
               and ft.type = 'ENTRADA'
               and ft.category is distinct from 'aporte_ou_movimentacao'
               and ft.occurred_at >= months.month_start
               and ft.occurred_at < months.month_start + interval '1 month'
          ), 0) as amount
        from generate_series(
          date_trunc('month', current_date) - interval '5 months',
          date_trunc('month', current_date),
          interval '1 month'
        ) as months(month_start)
      ) series
    )
  );
end;
$function$;

alter function public.get_cashflow_unchecked(text) owner to postgres;
comment on function public.get_cashflow_unchecked(text) is
  'Implementacao owner-only do caixa por evento: ENTRADAS brutas no credito e SAIDAS de estorno na data real do provedor; valores em aberto permanecem brutos.';
revoke all on function public.get_cashflow_unchecked(text)
  from public, anon, authenticated, service_role;
grant execute on function public.get_cashflow_unchecked(text)
  to postgres, supabase_admin;

-- As demais funcoes sao extensas e ja possuem regras de permissao, custo e
-- rateio auditadas. A substituicao assertiva abaixo troca somente a definicao
-- de receita realizada. Cada quantidade e verificada antes do CREATE OR REPLACE;
-- qualquer drift futuro faz a migration abortar em vez de alterar SQL errado.
do $net_revenue_reports$
declare
  patch record;
  v_definition text;
  v_old_occurrences integer;
  v_new_occurrences integer;
begin
  for patch in
    select *
      from (values
        (
          'public.dre_gerencial(text,text)',
          $old$SELECT COALESCE(sum(value),0) INTO v_receita$old$,
          $new$SELECT COALESCE(sum(greatest(round(coalesce(value, 0) - coalesce(refunded_amount, 0), 2), 0)),0) INTO v_receita$new$,
          1
        ),
        (
          'public.dre_gerencial(text,text)',
          $old$to_char(COALESCE(paid_at, payment_date, due_date),'YYYY-MM')$old$,
          $new$to_char(COALESCE(credited_at, paid_at, payment_date, due_date),'YYYY-MM')$new$,
          1
        ),
        (
          'public.dre_gerencial(text,text)',
          $old$WHERE ft.tenant_id = v_tenant AND ft.type = 'SAIDA'
      AND to_char(COALESCE(ft.occurred_at, ft.created_at),'YYYY-MM') = v_month$old$,
          $new$WHERE ft.tenant_id = v_tenant AND ft.type = 'SAIDA'
      AND ft.category IS DISTINCT FROM 'teacher_payout'
      AND ft.refund_student_payment_id IS NULL
      AND to_char(COALESCE(ft.occurred_at, ft.created_at),'YYYY-MM') = v_month$new$,
          1
        ),
        (
          'public.director_teacher_margin(text)',
          $old$sum(COALESCE(sp.value, sp.amount_cents / 100.0))$old$,
          $new$sum(greatest(round(coalesce(sp.value, 0) - coalesce(sp.refunded_amount, 0), 2), 0))$new$,
          2
        ),
        (
          'public.director_teacher_margin(text)',
          $old$sp.status IN ('RECEIVED','CONFIRMED','PAID','RECEIVED_IN_CASH')$old$,
          $new$sp.status IN ('RECEIVED','RECEIVED_IN_CASH')$new$,
          2
        ),
        (
          'public.director_teacher_margin(text)',
          $old$COALESCE(sp.paid_at::date, sp.payment_date, sp.due_date)$old$,
          $new$COALESCE(sp.credited_at::date, sp.paid_at::date, sp.payment_date, sp.due_date)$new$,
          2
        ),
        (
          'public.balancete_professores(text,text)',
          $old$sum(sp.value)$old$,
          $new$sum(greatest(round(coalesce(sp.value, 0) - coalesce(sp.refunded_amount, 0), 2), 0))$new$,
          4
        ),
        (
          'public.balancete_professores(text,text)',
          $old$COALESCE(sp.paid_at, sp.payment_date, sp.due_date)$old$,
          $new$COALESCE(sp.credited_at, sp.paid_at, sp.payment_date, sp.due_date)$new$,
          4
        ),
        (
          'public.balancete_receita_sem_aula(text,text)',
          $old$sum(sp.value)$old$,
          $new$sum(greatest(round(coalesce(sp.value, 0) - coalesce(sp.refunded_amount, 0), 2), 0))$new$,
          1
        ),
        (
          'public.balancete_receita_sem_aula(text,text)',
          $old$COALESCE(sp.paid_at, sp.payment_date, sp.due_date)$old$,
          $new$COALESCE(sp.credited_at, sp.paid_at, sp.payment_date, sp.due_date)$new$,
          1
        ),
        (
          'public.financial_reconciliation(text)',
          $old$coalesce((select sum(sp.value) from public.student_payments sp
                     where sp.student_id = p.id
                       and sp.status in ('RECEIVED', 'RECEIVED_IN_CASH')), 0) as recebido$old$,
          $new$coalesce((select sum(greatest(round(coalesce(sp.value, 0) - coalesce(sp.refunded_amount, 0), 2), 0)) from public.student_payments sp
                     where sp.student_id = p.id
                       and sp.status in ('RECEIVED', 'RECEIVED_IN_CASH')), 0) as recebido$new$,
          1
        )
      ) as replacements(signature, old_sql, new_sql, expected_occurrences)
  loop
    if to_regprocedure(patch.signature) is null then
      raise exception 'required financial report function is missing: %', patch.signature;
    end if;

    select pg_get_functiondef(to_regprocedure(patch.signature))
      into v_definition;
    v_old_occurrences := (
      length(v_definition) - length(replace(v_definition, patch.old_sql, ''))
    ) / length(patch.old_sql);
    v_new_occurrences := (
      length(v_definition) - length(replace(v_definition, patch.new_sql, ''))
    ) / length(patch.new_sql);

    if v_old_occurrences = patch.expected_occurrences
       and v_new_occurrences = 0 then
      execute replace(v_definition, patch.old_sql, patch.new_sql);
    elsif v_old_occurrences = 0
          and v_new_occurrences = patch.expected_occurrences then
      null;
    else
      raise exception
        'financial report drift for %: expected OLD=%/NEW=0 or OLD=0/NEW=%; found OLD=%/NEW=%',
        patch.signature,
        patch.expected_occurrences,
        patch.expected_occurrences,
        v_old_occurrences,
        v_new_occurrences;
    end if;

    select pg_get_functiondef(to_regprocedure(patch.signature))
      into v_definition;
    v_old_occurrences := (
      length(v_definition) - length(replace(v_definition, patch.old_sql, ''))
    ) / length(patch.old_sql);
    v_new_occurrences := (
      length(v_definition) - length(replace(v_definition, patch.new_sql, ''))
    ) / length(patch.new_sql);

    if v_old_occurrences <> 0
       or v_new_occurrences <> patch.expected_occurrences then
      raise exception
        'financial report patch postcondition failed for %: OLD=%/NEW=%',
        patch.signature,
        v_old_occurrences,
        v_new_occurrences;
    end if;
  end loop;
end
$net_revenue_reports$;

comment on function public.dre_gerencial(text, text) is
  'DRE por competencia: recebimentos liquidos de refunded_amount; custos pela aula. CONFIRMED nao e receita.';
comment on function public.director_teacher_margin(text) is
  'Custo e margem por professor com receita recebida liquida de refunded_amount. CONFIRMED nao e caixa.';
comment on function public.balancete_professores(text, text) is
  'Balancete por professor: receita realizada liquida de refunded_amount; receita contratada permanece bruta.';
comment on function public.balancete_receita_sem_aula(text, text) is
  'Receita recebida sem aula, liquida de refunded_amount, sem criar margem artificial para professor.';
comment on function public.financial_reconciliation(text) is
  'Reconciliacao usa recebimento liquido de refunded_amount para cobertura; faturas ainda em aberto permanecem pelo bruto.';

do $report_postconditions$
declare
  v_definition text;
  v_signature text;
begin
  select pg_get_functiondef('public.get_cashflow_unchecked(text)'::regprocedure)
    into v_definition;
  if position('public.financial_transactions' in v_definition) = 0
     or position('aporte_ou_movimentacao' in v_definition) = 0
     or position('sp.refunded_amount' in v_definition) > 0 then
    raise exception 'get_cashflow_unchecked is not using the canonical event ledger';
  end if;

  foreach v_signature in array array[
    'public.dre_gerencial(text,text)',
    'public.director_teacher_margin(text)',
    'public.balancete_professores(text,text)',
    'public.balancete_receita_sem_aula(text,text)',
    'public.financial_reconciliation(text)'
  ] loop
    select pg_get_functiondef(to_regprocedure(v_signature))
      into v_definition;
    if position('refunded_amount' in v_definition) = 0 then
      raise exception 'report % is not net of refunded_amount', v_signature;
    end if;
    if v_signature = 'public.dre_gerencial(text,text)'
       and position('refund_student_payment_id IS NULL' in v_definition) = 0 then
      raise exception 'dre_gerencial is double-counting refund events as expenses';
    end if;
  end loop;
end
$report_postconditions$;

-- -------------------------------------------------------------------------
-- 9. Pos-condicoes: a migration falha inteira se qualquer invariante falhar
-- -------------------------------------------------------------------------

do $postconditions$
begin
  if exists (
    select 1
      from public.financial_transactions ft
     where ft.amount_cents <> round(ft.amount * 100)::integer
  ) then
    raise exception 'financial_transactions amount equivalence failed';
  end if;

  if exists (
    select 1
      from public.student_payments sp
     where not (
       (sp.value is null and sp.amount_cents is null)
       or (
         sp.value is not null
         and sp.amount_cents is not null
         and sp.amount_cents = round(sp.value * 100)::integer
       )
     )
  ) then
    raise exception 'student_payments amount equivalence failed';
  end if;

  if exists (
    select 1
      from public.student_payments sp
      join public.financial_transactions ft on ft.student_payment_id = sp.id
     where sp.status <> 'REFUNDED'
       and (
         sp.status not in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
         or sp.tenant_id is null
         or coalesce(sp.value, 0) <= 0
       )
  ) then
    raise exception 'non-canonical student payment still has a ledger entry';
  end if;

  if exists (
    select 1
      from public.student_payments sp
     where (
         sp.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
         or (sp.status = 'REFUNDED' and sp.credited_at is not null)
       )
       and sp.tenant_id is not null
       and coalesce(sp.value, 0) > 0
       and not exists (
         select 1
           from public.financial_transactions ft
          where ft.student_payment_id = sp.id
       )
  ) then
    raise exception 'cash student payment is missing its ledger entry';
  end if;

  if exists (
    select 1
      from public.student_payments sp
      join public.financial_transactions ft on ft.student_payment_id = sp.id
     where (
         sp.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
         or (sp.status = 'REFUNDED' and sp.credited_at is not null)
       )
       and sp.tenant_id is not null
       and coalesce(sp.value, 0) > 0
       and (
         ft.tenant_id is distinct from sp.tenant_id
         or ft.type is distinct from 'ENTRADA'
         or ft.category is distinct from case
           when sp.status = 'NAO_RECEITA' then 'aporte_ou_movimentacao'
           else 'MENSALIDADE'
         end
         or ft.amount is distinct from round(sp.value, 2)
         or ft.amount_cents is distinct from round(sp.value * 100)::integer
         or ft.reference_id is distinct from sp.student_id
         or ft.occurred_at is distinct from coalesce(
           sp.credited_at,
           sp.paid_at,
           sp.payment_date + interval '12 hours',
           sp.due_date + interval '12 hours',
           ft.occurred_at
         )
       )
  ) then
    raise exception 'student payment ledger fields diverge from canonical payment data';
  end if;

  if exists (
    select 1
      from public.financial_transactions ft
     where ft.refund_student_payment_id is not null
       and (
         ft.student_payment_id is not null
         or ft.type <> 'SAIDA'
         or ft.amount <= 0
         or ft.category not in (
           'ESTORNO_MENSALIDADE',
           'estorno_aporte_ou_movimentacao'
         )
         or ft.provider_event_id is null
         or length(trim(ft.provider_event_id)) not between 1 and 240
       )
  ) then
    raise exception 'refund ledger row has a non-canonical shape';
  end if;

  if exists (
    select 1
      from public.financial_transactions ft
      join public.student_payments sp on sp.id = ft.refund_student_payment_id
     where ft.category is distinct from case
       when sp.status = 'NAO_RECEITA'
         then 'estorno_aporte_ou_movimentacao'
       else 'ESTORNO_MENSALIDADE'
     end
  ) then
    raise exception 'refund ledger category diverges from payment classification';
  end if;

  if exists (
    select 1
      from public.student_payments sp
      join lateral (
        select coalesce(sum(ft.amount), 0) as total
          from public.financial_transactions ft
         where ft.refund_student_payment_id = sp.id
      ) refunds on true
     where refunds.total > coalesce(sp.refunded_amount, 0)
  ) then
    raise exception 'refund event ledger exceeds the cumulative provider refund';
  end if;

  if exists (
    select 1
      from public.student_payments sp
     where sp.status in ('RECEIVED', 'RECEIVED_IN_CASH', 'NAO_RECEITA')
       and sp.credited_at is not null
       and sp.paid_at is distinct from sp.credited_at
  ) then
    raise exception 'credited_at is not reflected in paid_at';
  end if;

  if not exists (
    select 1
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      join pg_index i on i.indexrelid = c.oid
     where n.nspname = 'public'
       and c.relname = 'uq_financial_transactions_student_payment'
       and i.indisunique
       and i.indrelid = 'public.financial_transactions'::regclass
       and i.indnkeyatts = 1
       and i.indkey[0] = (
         select a.attnum
           from pg_attribute a
          where a.attrelid = 'public.financial_transactions'::regclass
            and a.attname = 'student_payment_id'
            and not a.attisdropped
       )
       and pg_get_expr(i.indpred, i.indrelid) = '(student_payment_id IS NOT NULL)'
  ) then
    raise exception 'student payment ledger unique index definition diverged';
  end if;

  if not exists (
    select 1
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      join pg_index i on i.indexrelid = c.oid
     where n.nspname = 'public'
       and c.relname = 'uq_financial_transactions_refund_event'
       and i.indisunique
       and i.indrelid = 'public.financial_transactions'::regclass
       and i.indnkeyatts = 1
       and i.indkey[0] = (
         select a.attnum
           from pg_attribute a
          where a.attrelid = 'public.financial_transactions'::regclass
            and a.attname = 'provider_event_id'
            and not a.attisdropped
       )
       and pg_get_expr(i.indpred, i.indrelid) =
         '((refund_student_payment_id IS NOT NULL) AND (provider_event_id IS NOT NULL))'
  ) then
    raise exception 'refund provider event unique index definition diverged';
  end if;

  if exists (
    select 1
      from public.student_payments sp
     where sp.ledger_entry_created is distinct from exists (
       select 1
         from public.financial_transactions ft
        where ft.student_payment_id = sp.id
     )
  ) then
    raise exception 'ledger_entry_created diverges from ledger existence';
  end if;
end
$postconditions$;

notify pgrst, 'reload schema';
