-- Derive a student's current financial status from the newest matured
-- competence instead of from whichever Asaas webhook happens to arrive last.
-- This prevents an old settlement from clearing a newer overdue charge and an
-- old overdue event from blocking a student whose current charge is settled.

create table if not exists public.student_financial_status_audit (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  student_id uuid not null,
  previous_status text,
  derived_status text not null check (
    derived_status in ('ACTIVE', 'OVERDUE', 'PENDING')
  ),
  controlling_due_date date not null,
  payment_snapshot jsonb not null,
  created_at timestamptz not null default pg_catalog.clock_timestamp()
);

create index if not exists student_financial_status_audit_student_idx
  on public.student_financial_status_audit (
    tenant_id, student_id, created_at desc
  );

alter table public.student_financial_status_audit owner to postgres;
alter table public.student_financial_status_audit enable row level security;
revoke all on table public.student_financial_status_audit
  from public, anon, authenticated, service_role;
revoke all on sequence public.student_financial_status_audit_id_seq
  from public, anon, authenticated, service_role;
grant select on table public.student_financial_status_audit to service_role;

comment on table public.student_financial_status_audit is
  'Immutable trace of aggregate financial-status changes derived from the newest matured student-payment competence.';

create or replace function public.recompute_student_financial_status(
  p_tenant_id text,
  p_student_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  normalized_tenant text := nullif(
    pg_catalog.btrim(coalesce(p_tenant_id, '')),
    ''
  );
  profile_row public.profiles%rowtype;
  controlling_due_date date;
  derived_status text;
  payment_snapshot jsonb;
begin
  if coalesce((select auth.jwt() ->> 'role'), '') <> 'service_role' then
    raise exception 'service_role_required' using errcode = '42501';
  end if;
  if normalized_tenant is null or p_student_id is null then
    raise exception 'invalid_student_financial_scope' using errcode = '22023';
  end if;

  -- This row lock serializes different payment webhooks for one student. The
  -- payment snapshots themselves have already committed before this RPC runs.
  select profile.*
    into profile_row
    from public.profiles as profile
   where profile.id = p_student_id
   for update;

  if profile_row.id is null then
    return pg_catalog.jsonb_build_object(
      'ok', true,
      'action', 'PROFILE_MISSING'
    );
  end if;
  if profile_row.tenant_id is distinct from normalized_tenant
     or profile_row.role is distinct from 'STUDENT'
  then
    raise exception 'student_financial_scope_mismatch' using errcode = '42501';
  end if;
  if pg_catalog.lower(pg_catalog.btrim(coalesce(
       profile_row.lifecycle_status,
       ''
     ))) <> 'active'
     or pg_catalog.upper(pg_catalog.btrim(coalesce(
       profile_row.status_financial,
       ''
     ))) = 'ARCHIVED'
  then
    return pg_catalog.jsonb_build_object(
      'ok', true,
      'action', 'PRESERVED',
      'status', profile_row.status_financial
    );
  end if;

  select pg_catalog.max(payment.due_date)
    into controlling_due_date
    from public.student_payments as payment
   where payment.tenant_id = normalized_tenant
     and payment.student_id = p_student_id
     and payment.due_date is not null
     and payment.due_date <= current_date
     and pg_catalog.upper(pg_catalog.btrim(coalesce(payment.status, ''))) in (
       'OVERDUE',
       'RECEIVED',
       'RECEIVED_IN_CASH',
       'PAGO',
       'PAYMENT_RECEIVED',
       'PAYMENT_RECEIVED_IN_CASH',
       'REFUNDED',
       'REVERSED'
     );

  if controlling_due_date is null then
    return pg_catalog.jsonb_build_object(
      'ok', true,
      'action', 'NO_MATURED_PAYMENT',
      'status', profile_row.status_financial
    );
  end if;

  select
    case
      -- Multiple legacy rows may share a competence. Never clear a proven
      -- outstanding charge merely because another row on that day settled.
      when pg_catalog.bool_or(
        pg_catalog.upper(pg_catalog.btrim(coalesce(payment.status, ''))) =
          'OVERDUE'
      ) then 'OVERDUE'
      when pg_catalog.bool_or(
        pg_catalog.upper(pg_catalog.btrim(coalesce(payment.status, ''))) in (
          'RECEIVED',
          'RECEIVED_IN_CASH',
          'PAGO',
          'PAYMENT_RECEIVED',
          'PAYMENT_RECEIVED_IN_CASH'
        )
      ) then 'ACTIVE'
      when pg_catalog.bool_or(
        pg_catalog.upper(pg_catalog.btrim(coalesce(payment.status, ''))) in (
          'REFUNDED',
          'REVERSED'
        )
      ) then 'PENDING'
      -- CREATED/CONFIRMED/PENDING and the manual NAO_RECEITA accounting
      -- classification are not proof that a tuition payment granted access.
      else null
    end,
    pg_catalog.jsonb_agg(
      pg_catalog.jsonb_build_object(
        'id', payment.id,
        'providerPaymentId', payment.asaas_payment_id,
        'status', payment.status,
        'providerStatus', payment.provider_status
      ) order by payment.id
    )
    into derived_status, payment_snapshot
    from public.student_payments as payment
   where payment.tenant_id = normalized_tenant
     and payment.student_id = p_student_id
     and payment.due_date = controlling_due_date;

  if derived_status is null then
    return pg_catalog.jsonb_build_object(
      'ok', true,
      'action', 'NO_DECISIVE_CHANGE',
      'status', profile_row.status_financial,
      'controlling_due_date', controlling_due_date
    );
  end if;

  if pg_catalog.upper(pg_catalog.btrim(coalesce(
       profile_row.status_financial,
       ''
     ))) = derived_status
  then
    return pg_catalog.jsonb_build_object(
      'ok', true,
      'action', 'UNCHANGED',
      'status', derived_status,
      'controlling_due_date', controlling_due_date
    );
  end if;

  insert into public.student_financial_status_audit (
    tenant_id,
    student_id,
    previous_status,
    derived_status,
    controlling_due_date,
    payment_snapshot
  ) values (
    normalized_tenant,
    p_student_id,
    profile_row.status_financial,
    derived_status,
    controlling_due_date,
    coalesce(payment_snapshot, '[]'::jsonb)
  );

  update public.profiles as profile
     set status_financial = derived_status
   where profile.id = p_student_id
     and profile.tenant_id = normalized_tenant
     and profile.role = 'STUDENT'
     and pg_catalog.lower(pg_catalog.btrim(coalesce(
       profile.lifecycle_status,
       ''
     ))) = 'active'
     and pg_catalog.upper(pg_catalog.btrim(coalesce(
       profile.status_financial,
       ''
     ))) <> 'ARCHIVED';

  if not found then
    raise exception 'student_financial_profile_changed_during_recompute'
      using errcode = '40001';
  end if;

  return pg_catalog.jsonb_build_object(
    'ok', true,
    'action', 'UPDATED',
    'status', derived_status,
    'controlling_due_date', controlling_due_date
  );
end;
$function$;

alter function public.recompute_student_financial_status(text, uuid)
  owner to postgres;
revoke all on function public.recompute_student_financial_status(text, uuid)
  from public, anon, authenticated;
grant execute on function public.recompute_student_financial_status(text, uuid)
  to service_role;

-- Reconcile existing active students once, with the same auditable rule used
-- by future webhooks. Replaying this migration is harmless because unchanged
-- results do not create audit rows.
do $backfill$
declare
  candidate record;
begin
  perform pg_catalog.set_config(
    'request.jwt.claims',
    '{"role":"service_role"}',
    true
  );
  for candidate in
    select profile.tenant_id, profile.id
      from public.profiles as profile
     where profile.role = 'STUDENT'
       and profile.tenant_id is not null
       and pg_catalog.lower(pg_catalog.btrim(coalesce(
         profile.lifecycle_status,
         ''
       ))) = 'active'
       and pg_catalog.upper(pg_catalog.btrim(coalesce(
         profile.status_financial,
         ''
       ))) <> 'ARCHIVED'
       and exists (
         select 1
           from public.student_payments as payment
          where payment.tenant_id = profile.tenant_id
            and payment.student_id = profile.id
            and payment.due_date <= current_date
            and pg_catalog.upper(pg_catalog.btrim(coalesce(
              payment.status,
              ''
            ))) in (
              'OVERDUE',
              'RECEIVED',
              'RECEIVED_IN_CASH',
              'PAGO',
              'PAYMENT_RECEIVED',
              'PAYMENT_RECEIVED_IN_CASH',
              'REFUNDED',
              'REVERSED'
            )
       )
  loop
    perform public.recompute_student_financial_status(
      candidate.tenant_id,
      candidate.id
    );
  end loop;
end;
$backfill$;
