import type { HubVideoContent, HubVideoSlug } from '../types';

export const VIDEO_WIDTH = 1920;
export const VIDEO_HEIGHT = 1080;
export const VIDEO_FPS = 30;

export const HUB_VIDEOS: HubVideoContent[] = [
  {
    id: 'HubOverviewPtBr',
    slug: 'hub-overview',
    productName: 'Wise Wolf Hub',
    eyebrow: 'Infraestrutura para professores e escolas',
    title: 'Da primeira aula à',
    emphasis: 'operação inteira.',
    accent: '#ff785f',
    secondaryAccent: '#7652ed',
    mockup: 'ecosystem',
    problemHeadline: 'Dez ferramentas não formam uma jornada.',
    problemItems: ['Planejamento disperso', 'Prática sem continuidade', 'Operação sem contexto'],
    productHeadline: 'Quatro soluções. Um próximo passo claro.',
    proofHeadline: 'Complexidade por trás. Clareza na frente.',
    proofItems: ['Ensinar com intenção', 'Engajar entre as aulas', 'Crescer com processo', 'Operar com isolamento'],
    cta: 'Escolha sua jornada',
    ctaButtons: ['Sou professor', 'Tenho uma escola'],
    ctaSupport: 'Professor autônomo ou escola de idiomas',
    narration: [
      { scene: 'hook', text: 'Ensinar bem não deveria exigir dez ferramentas desconectadas.' },
      { scene: 'problem', text: 'O ecossistema Wise Wolf reúne o que professores e escolas precisam para planejar, engajar, crescer e operar.' },
      { scene: 'product', text: 'Biblioteca com curadoria. Educador com inteligência artificial e contexto. Prática real com o Wolfie. E uma operação escolar conectada, do primeiro contato à renovação.' },
      { scene: 'proof', text: 'Cada acesso respeita conta, papel e ambiente, para que a experiência seja simples na frente e segura por trás.' },
      { scene: 'cta', text: 'Você escolhe onde está. A Wise Wolf organiza o próximo passo. Conheça o Hub.' },
    ],
  },
  {
    id: 'HubLibraryPtBr',
    slug: 'library',
    productName: 'Wise Wolf Library',
    eyebrow: 'Acervo para professores de inglês',
    title: 'Pare de procurar material.',
    emphasis: 'Escolha com intenção.',
    accent: '#d66a45',
    secondaryAccent: '#ffad70',
    mockup: 'library',
    problemHeadline: 'A preparação não precisa começar no caos.',
    problemItems: ['Pastas dispersas', 'Links sem contexto', 'Conteúdo sem origem clara'],
    productHeadline: 'Filtre. Avalie. Leve para a aula.',
    proofHeadline: 'Curadoria que respeita contexto e acesso.',
    proofItems: ['Níveis de A1 a C2', 'Filtros por objetivo', 'Prévia antes do arquivo', 'Conteúdo protegido'],
    cta: 'Testar a Biblioteca',
    ctaButtons: ['Testar a Biblioteca'],
    ctaSupport: 'Menos improviso. Mais intenção pedagógica.',
    narration: [
      { scene: 'hook', text: 'Quanto tempo de uma boa aula desaparece procurando material?' },
      { scene: 'problem', text: 'Pastas, links e arquivos dispersos transformam preparação em improviso antes mesmo da aula começar.' },
      { scene: 'product', text: 'Na Wise Wolf Library, você filtra por nível, contexto e objetivo, avalia a prévia e encontra uma base pronta para adaptar.' },
      { scene: 'proof', text: 'O catálogo mostra somente conteúdos autorizados. O arquivo completo é liberado apenas para contas e planos com permissão.' },
      { scene: 'cta', text: 'Prepare menos no improviso e ensine com mais intenção. Experimente a Biblioteca.' },
    ],
  },
  {
    id: 'HubEducadorIaPtBr',
    slug: 'educator-ai',
    productName: 'Educador IA',
    eyebrow: 'Planejamento pedagógico com contexto',
    title: 'A inteligência não começa pela atividade.',
    emphasis: 'Começa pelo resultado.',
    accent: '#7652ed',
    secondaryAccent: '#b89cff',
    mockup: 'educator',
    problemHeadline: 'Prompt genérico entra. Aula genérica sai.',
    problemItems: ['Objetivo pouco claro', 'Atividades sem sequência', 'Plano difícil de aplicar'],
    productHeadline: 'Contexto vira uma sequência ensinável.',
    proofHeadline: 'A inteligência estrutura. Você decide.',
    proofItems: ['Resultado primeiro', 'Nível e duração', 'Sequência completa', 'Base pronta para adaptar'],
    cta: 'Criar meu primeiro plano',
    ctaButtons: ['Criar meu primeiro plano'],
    ctaSupport: 'Mais tempo para observar e ensinar.',
    narration: [
      { scene: 'hook', text: 'Um plano de aula forte não começa em um pedido genérico para uma inteligência artificial.' },
      { scene: 'problem', text: 'Sem resultado, nível e duração, surgem atividades bonitas, mas desconectadas da realidade do aluno.' },
      { scene: 'product', text: 'Com o Educador IA, você define o que o aluno precisa alcançar. O contexto vira aquecimento, prática guiada e continuidade.' },
      { scene: 'proof', text: 'A inteligência organiza uma primeira versão. Você adapta, decide a abordagem e conduz a experiência.' },
      { scene: 'cta', text: 'Menos tempo formatando. Mais tempo ensinando. Crie seu primeiro plano.' },
    ],
  },
  {
    id: 'HubWolfiePtBr',
    slug: 'wolfie',
    productName: 'Wolfie AI Tutor',
    eyebrow: 'Prática de inglês para situações reais',
    title: 'Pratique antes de o inglês',
    emphasis: 'virar uma situação real.',
    accent: '#20a9cc',
    secondaryAccent: '#5de1cf',
    mockup: 'wolfie',
    problemHeadline: 'A confiança é construída antes.',
    problemItems: ['Medo de errar em público', 'Pouco contato ativo', 'Longos intervalos entre aulas'],
    productHeadline: 'Seu contexto entra na conversa.',
    proofHeadline: 'Um espaço privado para tentar e repetir.',
    proofItems: ['Entrevistas', 'Viagens', 'Reuniões', 'Rotina e interesses'],
    cta: 'Conhecer o Wolfie',
    ctaButtons: ['Conhecer os planos Wolfie'],
    ctaSupport: 'Prática contextual disponível quando você precisa.',
    narration: [
      { scene: 'hook', text: 'A confiança não nasce quando chega a situação real. Ela é construída antes.' },
      { scene: 'problem', text: 'Entre uma aula e outra, o inglês pode voltar a ser silêncio, insegurança e pouca prática ativa.' },
      { scene: 'product', text: 'Com o Wolfie, o aluno pratica conversas ligadas ao próprio nível, objetivo e rotina. Entrevistas, viagens, reuniões ou desafios do dia a dia.' },
      { scene: 'proof', text: 'É um espaço privado para tentar, repetir e evoluir. O professor orienta. O Wolfie amplia a prática.' },
      { scene: 'cta', text: 'Chegue mais confiante à próxima situação real. Conheça o Wolfie.' },
    ],
  },
  {
    id: 'HubSchoolOsPtBr',
    slug: 'school-os',
    productName: 'Wise Wolf School OS',
    eyebrow: 'Sistema para escolas de idiomas',
    title: 'Sua escola não precisa crescer',
    emphasis: 'em processos soltos.',
    accent: '#258e79',
    secondaryAccent: '#8ad9b7',
    mockup: 'school',
    problemHeadline: 'Crescer sem contexto cria pontos cegos.',
    problemItems: ['Comercial separado', 'Agenda fragmentada', 'Acessos amplos demais'],
    productHeadline: 'Do novo contato à renovação.',
    proofHeadline: 'Sua marca aparece. Outros dados, nunca.',
    proofItems: ['Ambiente por escola', 'Papéis por função', 'Credenciais protegidas', 'Implantação assistida'],
    cta: 'Solicitar demonstração',
    ctaButtons: ['Solicitar demonstração'],
    ctaSupport: 'Veja sua operação inteira com mais clareza.',
    narration: [
      { scene: 'hook', text: 'Uma escola não cresce bem com agenda, matrícula, contratos e cobrança em lugares diferentes.' },
      { scene: 'problem', text: 'Quando cada área carrega uma versão da operação, o contexto se perde e os pontos cegos aparecem.' },
      { scene: 'product', text: 'O Wise Wolf School OS conecta comercial, pedagógico, equipe e financeiro, do novo contato à próxima renovação.' },
      { scene: 'proof', text: 'Cada escola tem seu próprio ambiente, sua marca, suas credenciais e permissões por função. Os dados permanecem isolados.' },
      { scene: 'cta', text: 'Solicite uma demonstração e veja sua operação inteira com mais clareza.' },
    ],
  },
];

export const HUB_VIDEO_BY_SLUG = Object.fromEntries(
  HUB_VIDEOS.map((video) => [video.slug, video]),
) as Record<HubVideoSlug, HubVideoContent>;
